apiVersion: v1
data:
  mongodb-root-password: Q3NKU2ZNOEt1eQ==
kind: Secret
metadata:
  name: mongo-mongodb
  namespace: sasha-the-king
type: Opaque
---
apiVersion: v1
data:
  client-passwords: UTdvMUszc0FyWA==
  controller-password: SlcxM3dvS1pnNQ==
  inter-broker-password: VzZFOE1HUFZESQ==
  system-user-password: UTdvMUszc0FyWA==
kind: Secret
metadata:
  name: kafka-user-passwords
  namespace: sasha-the-king
type: Opaque
